# Generated by Django 5.2.7 on 2025-10-22 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteDeStock',
            fields=[
                ('sku', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('lote_numero', models.CharField(max_length=100, verbose_name='Número de Lote')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='productos.producto')),
            ],
        ),
    ]
