# Generated by Django 5.2.7 on 2025-10-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=100, unique=True, verbose_name='Código de barras')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('formato', models.CharField(max_length=100, verbose_name='Formato')),
            ],
        ),
    ]
